<?php
                        //function to make life easy with menu
                        $m=array();
                        $this->load->helper('inflector');
                        function li($href,$msg){
                            $s=sprintf('<li><a href="../%s/1" >%s</a></li>',$href,humanize($msg));
                            $m[]=$s;
                            echo $s;
                        }
                        li('tom-chambers','TOM CHAMBERS Gallery');
                        li('simon-procter','Simon Procter Gallery');
                        li('martin-schoeller','MARTIN SCHOELLER  Portraits Gallery');
                        li('zemotion_files','Zemotion amazing gallery');
                        li('mariano-vivanco','Mariano Vivanco photography');
                        li('loretta-lux','LORETTA LUX Gallery');

                        li('eugenio-recuenco','Eugenio Recuenco gallery');
                        li('eugenio-china','Eugenio Recuenco China Posters');
                        li('eugenio-01','Eugenio Recuenco 01');
                        li('eugenio-02','Eugenio Recuenco 02');
                        li('eugenio-03','Eugenio Recuenco 03');
                        li('eugenio-04','Eugenio Recuenco 04');
                        li('eugenio-05','Eugenio Recuenco 05');
                        li('eugenio-06','Eugenio Recuenco 06');
                        li('eugenio-07','Eugenio Recuenco 07');
                        li('eugenio-08','Eugenio Recuenco 08');
                        li('eugenio-09','Eugenio Recuenco 09');
                        li('eugenio-010','Eugenio Recuenco 010');
                        li('eugenio-011','Eugenio Recuenco 011');
                        li('eugenio-012','Eugenio Recuenco 012');
                        li('eugenio-013','Eugenio Recuenco 013');
                        li('eugenio-014','Eugenio Recuenco 014');
                        li('eugenio-015','Eugenio Recuenco 015');
                        li('eugenio-016','Eugenio Recuenco 016');
                        li('eugenio-017','Eugenio Recuenco 017');
                        li('eugenio-018','Eugenio Recuenco 018');
                        li('eugenio-019','Eugenio Recuenco 019');
                        li('eugenio-020','Eugenio Recuenco 020');

                        li('paolo-zambalti-01','Paolo Zamabalti 01');
                        li('paolo-zambalti-02','Paolo Zamabalti 02');
                        li('paolo-zambalti-03','Paolo Zamabalti 03');
                        li('paolo-zambalti-04','Paolo Zamabalti 04');
                        li('paolo-zambalti-05','Paolo Zamabalti 05');

                        li('jose-aragon-01','Jose Aragon 01 Gallery');
                        li('jose-aragon-02','Jose Aragon 02 Gallery');
                        li('jose-aragon-03','Jose Aragon 03 Gallery');
                        li('jose-aragon-04','Jose Aragon 04 Gallery');
                        li('nazif-01','Nazif Topcuoglu 01 Gallery');
                        li('nazif-02','Nazif Topcuoglu 02 Gallery');
                        li('nazif-03','Nazif Topcuoglu 03 Gallery');
                        li('bruno-dayan-01','Bruno Dayan 01 Gallery');
                        li('bruno-dayan-02','Bruno Dayan 02 Gallery');
                        li('bruno-dayan-03','Bruno Dayan 03 Gallery');
                        li('bruno-dayan-04','Bruno Dayan 04 Gallery');
                        li('yves-krief-01','Yves Krief 01 Gallery');
                        li('lev-daichik','Lev daichik');
                        li('rudolf-kartelin','Rudolf Kartelin');
                        li('alexei-nikishin','Alexei Nikishin');
                        li('massimo-santoni','Massimo Santoni');
                        li('pavel-kaplun','Pavel Kaplun');
                        li('jacqueline-roberts','Jacqueline Roberts');
                        li('noel-tri-rahardjo','Noel Tri Rahardjo');
                        li('musin-yohan','Musin Yohan');
                        li('hataiiia','Hataiiia');
                        li('hataiiia-01','Hataiiia 01');
                        li('hataiiia-02','Hataiiia 02');
                        li('hataiiia-03','Hataiiia 03');
                        li('tony-dudley','Tony Dudley');
                        li('t-carlos','T carlos');
                        li('katerina-lomonosov','Katerina Lomonosov');
                        li('i-dani','I Dani (photonet)');
                        li('maurizio-moro','maurizio Moro');
                        li('axel-bueckert','Axel Bueckert');
                        li('valery-lemberg','Vlery Lemberg');
                        li('massimiliano-uccelletti','Massimiliano Ucceletti (photonet)');
                        li('normunds-laizans','Normunds Laizans (photonet)');
                        li('Vladimir-Arkhipov','Vladimir Archipov (archipov.ru)');
                        li('Vladimir-Arkhipov-01','Vladimir Archipov 02 (archipov.ru)');


                        echo '<h3 style="margin-bottom:5px">Milen Lesemann</h3>';
                        li('milen-lesemann','Milen Lesemann Fine Nudes Color');
                        li('milen-lesemann-01','Milen Lesemann Fashion');
                        li('milen-lesemann-02','Milen Lesemann Fashion 2');
                        li('berenice-abbott','berenice-abbott-01');
                        li('berenice-abbott-01','berenice-abbott 02');
                        li('dorothea-lange','Dorothea Lange');
                        li('louis-hine','Louis Hine');
                        li('helen-levitt','Helen Levitt');
                        //li('pin-up-art/olivia-berardinis','Olivia Berardinis');
                        li('ilan-hamra','Ilan hamra');
                        li('aneta-kowalczyk','Aneta Kowalczyk Gallery');
                        li('aneta-kowalczyk-01','Aneta Kowalczyk Gallery 01');
                        li('aneta-kowalczyk-02','Aneta Kowalczyk Gallery 02');
                        li('jack-ratcliffe','Jack Radcliffe');
                        li('ritze-van-brug','Ritze-van-brug (behance)');
                        li('herman-leonard','Herman Leonard');
                        li('august-sander','August Sander');
                        li('lee-friedlander','Lee Friedlander');
                        li('elliott-erwitt','Elliott Erwitt - six decades');
                        li('walker_evans','Walker Evans');
                        li('che-guevara','Che Guevara');
                        li('Scott-8000','Betty');
                        li('horst','Horst');
                        li('horst-01','Horst');
                        li('arthur-leipzig','Arthur Leipzig');
                        li('marc-riboud','Marc Riboud');
                        li('willy-ronis','Willy Ronis');
                        li('athena-01','Athena & Wei in China');

                        li('steve-hanks','Steve Hanks');
                        li('alexander-sheversky','Alexander Sheversky');
                        li('imogen-cunningham','Imogen Cunningham');
                        li('rondal-partidge','Rondal Partidge');
                        li('suza-scalora','Suza Scalora');

                        li('peter-turnley','Peter Turnley');
                        li('marcus-ohlsson','Marcus Ohlsson');
                        li('marko-photographer','Marko Photographer');
                        li('inspiration','Inspiration');
                        li('jamie-cambell','Jamie Cambell');
                        li('sm','SM');
                        li('kattaca','Kattacs (Behance)');
                        li('annie-leibovitz','Annie Leibovitz');
                        li('eugina','Eugina at Deviant');
                        li('vladimir-kalinin','Vladimir Kalinin');
                        li('rudiger-schestag','Rudiger Schestag');
                        li('michael-magin','Michael Magin');
                        li('sylvie-blum','Sylvie Blum (Seenby)');
                        li('christian-weigel','Christian Weigel (Seenby)');
                        li('alexander-straulino','alexander-straulino (Seenby)');
                        li('laura-honse','laura-honse (Seenby)');
                        li('rodney-smith','Rodney smith');
                        li('pirelli','pirelli');
                        li('lavazza-2009','lavazza Coffee 2009');
                        li('nobuyoshi-araki','Nobuyoshi Araki');
                        li('miles-aldridge','Miles Aldridge');
                        li('vincent-peters','Vincent Peters');
                        li('notursweetie','NoturSweetie');
                        li('UK_Volume_I','UK Stamps Philips Collection Volume I');
                        li('UK_Volume_II','UK Stamps Philips Collection Volume II');
                        li('UK_Volume_III','UK Stamps Philips Collection Volume III');
                        li('UK_Volume_IV','UK Stamps Philips Collection Volume IV');
                        li('UK_Volume_V','UK Stamps Philips Collection Volume V');
                        li('UK_Volume_XXXIX','UK Stamps');
                        li('UK_Volume_XLV','UK Stamps XLV');
                        li('NDIA-November-5-2008','NDIA Start');
                        li('rodney-smith','Rodney Smith');
                        li('barrotti','Juliano Michelangelo Barrotti');
                      ?>


