
topic = new Topic();
Topic.prototype.cat='';
Topic.prototype.link='';
// categories object
cats ={categoryArray:[],                     // lists all the categories
       ucFirst:function(){
            for(var i;i<categoryArray.length;i++){
              categoryArray[i].toUpcase();
            }
       },
       length:function(){}
   };

// menu is an array of topics
menu=[
['Introduction','Javascript Introduction','jQuery'],
'Add table row with jQuery',
[{cat:'AJAX',
  link:'AJAX Part III',
  tags:''}
],
['AJAX','AJAX Part IV'],

'Array like objects',
'Base64',
'Bouncing Numbers',
'Bouncing Numbers Part II',
'Brendan Eich',
'Cadaeic Cadenza regex and pi',
['All Cretans are liars'],
'Canvas',
'Canvas Images',
'Canvas Support',
'Canvas the Flot plugin',
'Chaining',
'Chinese Counting Rods',
'Closures Part I',
'Closures Part II',
'Closure functions',
'Code Evaluation',
'Color Blender',
'Console',
'CSS Counters',
'Debouncing events',
'Debug',
'Developing Plugins Part I',
'DOM CSS',
'DOM Modification',
'Drag and Drop',
'Excursions into Numbers the Greek Numbering System',
'Excursions into Numbers the Greek Numbering System 2',
'Excursions into Numbers the Greek Numbering System 3',
'Formatter',
'Functional Programming',
'Functions and JQuery',
'Graphics Libraries jsxgraph',
'HasClass',
'How to add custom function',
'How to write a plugin',
'HTML prototype',
'Installing Clojure on Windows',

'Javascript arrays',
'Javascript Associative Arrays',
'Javascript Currying',
'Javascript Date Object',
'Javascript do while loops',
'Javascript Drawing Circles',
'Javascript Exception Handling',
'Javascript Expressions and Operators',
'Javascript False or True',
'Javascript for loops',
'Javascript Functions in Arrays',
'Javascript Functions Recursion',
'Javascript Function Properties and Methods',
'Javascript Math Object',
'Javascript Math Object Part II',
'Javascript More on Functions',
'Javascript Morse Code',
'Javascript prototype',
'Javascript prototype Part III',
'Javascript random numbers',
'Javascript Regular Expressions',
'Javascript Regular Expressions Part III',
'Javascript spigot algorithms',
'Javascript Strings',
'Javascript Switch',
'Javascript the new operator',
'Javascript timers',
'Javascript Timers Revisited',
'Javascript Unicode',
'Javascript Variable Number Arguments',
'JQuery and Lists',
'JQuery Arrays',
'JQuery Attributes toggleClass',
'JQuery binding events',
'JQuery Callbacks',
'JQuery Checkboxes',
'JQuery Content Filters',
'JQuery Content Filters has',
'JQuery Content Filters Parent',
'JQuery CSS Part I',
'JQuery determine if a font exists',
'JQuery Effects Cloning',
'JQuery Effects Part I',
'JQuery Effects Part II',
'JQuery Effects Toggle Part II',
'JQuery Events live',
'JQuery extend',
'JQuery extend the details',
'JQuery Form Handling',
'JQuery get all the colors',
'JQuery Handling Documents',
'JQuery Objects',
'JQuery Objects Part II',
'JQuery Plugins ColorBox',
'JQuery Plugins Colorpicker',
'JQuery Plugins Cycle',
'JQuery Plugins Flip',
'JQuery Plugins Flip Part II',
'JQuery Plugins in Field Labels',
'JQuery Plugins Metadata',
'JQuery Plugins ScrollTo',
'JQuery Progress',
'JQuery Selectors Introduction',
'JQuery Selectors nth Child',
'JQuery Siblings()',
'JQuery Siblings',
'JQuery the each method',
'JQuery the eq() method',
'JQuery the eq method',
'JQuery Tips',
'JQuery Visibility Filters',
'JQuery Writing Modal dialogs',
'JSLint',
'JSon',
'Ledger',
'Libraries',
'Libraries Animation Basics',
'Library currency',
'Maya Numbers',
'Memory leaks',
'Neurons and Music',
'Objects call and apply',
'Objects Private Variables',
'Opacity Transparency and the Alpha channel',
'Organizing your Code',
'Plugins Colorpickers Color Lovers',
'Printable',
'Processing',
'Regular Expression library',
'Sandbox',
'Sieve of Eratosthenes',
'Standalone Plugins',
'SVG Introduction',
'The Sixty One',
'The Sixty One Form',
'The Sixty One Part II',
'Timers Part II',
'Timers Part III',
'Typing tests',
'What',
'What you see is what is Run'];

